// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('ComponentsCtrl', [
    '$scope', function($scope) {
      return console.i("#/components initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=components.map
