// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('CSSCtrl', [
    '$scope', function($scope) {
      return console.i("#/css initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=css.map
