// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('CustomizeCtrl', [
    '$scope', function($scope) {
      return console.i("#/customize initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=customize.map
