// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('GettingStartedCtrl', [
    '$scope', function($scope) {
      return console.i("#/getting-started initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=getting-started.map
