// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('HomeCtrl', [
    '$scope', function($scope) {
      return console.i("#/home initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=home.map
