// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('JavaScriptCtrl', [
    '$scope', function($scope) {
      return console.i("#/javascript initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=javascript.map
