// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('NgBootstrapDocs').controller('FooterCtrl', [
    '$scope', function($scope) {
      return console.i("footer initialized");
    }
  ]);

}).call(this);

//# sourceMappingURL=footer.map
