// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module("NgBootstrapDocs", ["Angustrap", "ngRoute"]).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when("/", {
        templateUrl: "views/home.html",
        controller: "HomeCtrl"
      }).when("/getting-started", {
        templateUrl: "views/getting-started/index.html",
        controller: "GettingStartedCtrl"
      }).when("/css", {
        templateUrl: "views/css/index.html",
        controller: "CSSCtrl"
      }).when("/components", {
        templateUrl: "views/components/index.html",
        controller: "ComponentsCtrl"
      }).when("/javascript", {
        templateUrl: "views/javascript/index.html",
        controller: "JavaScriptCtrl"
      }).when("/customize", {
        templateUrl: "views/customize/index.html",
        controller: "CustomizeCtrl"
      }).otherwise({
        redirectTo: "/"
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=app.map
